@endpoint = http://localhost:8080/dashboard

### GET
GET http://localhost:8080/dashboard/all

## GET by number
GET http://localhost:8080/dashboard/33

### POST
POST {{ endpoint }}
Content-Type: application/json

{
  "numero": 33
}

### DELETE
DELETE http://localhost:8080/dashboard/46


### PUT
PUT http://localhost:8080/dashboard/47
Content-Type: application/json

{
  "aberta": true
}

### PATCH
PATCH http://localhost:8080/dashboard/31
Content-Type: application/json

{
  "produtos": [{"id": 1,"quantity": 1}]
}
